config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :families
  resources :locations
  resources :students
  

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout



  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # set the root url
  root to: 'home#index'

  # # Named routes
  # patch 'completed/:id' => 'tasks#complete', as: :complete
  # patch 'incomplete/:id' => 'tasks#incomplete', as: :incomplete
  
  # Last route in routes.rb that essentially handles routing errors
  get '*a', to: 'errors#routing'

end

app/models/location.rb
class Location < ActiveRecord::Base

  # relationships
  has_many :camps

  # states list
  STATES_LIST = [['Alabama', 'AL'],['Alaska', 'AK'],['Arizona', 'AZ'],['Arkansas', 'AR'],['California', 'CA'],['Colorado', 'CO'],['Connectict', 'CT'],['Delaware', 'DE'],['District of Columbia ', 'DC'],['Florida', 'FL'],['Georgia', 'GA'],['Hawaii', 'HI'],['Idaho', 'ID'],['Illinois', 'IL'],['Indiana', 'IN'],['Iowa', 'IA'],['Kansas', 'KS'],['Kentucky', 'KY'],['Louisiana', 'LA'],['Maine', 'ME'],['Maryland', 'MD'],['Massachusetts', 'MA'],['Michigan', 'MI'],['Minnesota', 'MN'],['Mississippi', 'MS'],['Missouri', 'MO'],['Montana', 'MT'],['Nebraska', 'NE'],['Nevada', 'NV'],['New Hampshire', 'NH'],['New Jersey', 'NJ'],['New Mexico', 'NM'],['New York', 'NY'],['North Carolina','NC'],['North Dakota', 'ND'],['Ohio', 'OH'],['Oklahoma', 'OK'],['Oregon', 'OR'],['Pennsylvania', 'PA'],['Rhode Island', 'RI'],['South Carolina', 'SC'],['South Dakota', 'SD'],['Tennessee', 'TN'],['Texas', 'TX'],['Utah', 'UT'],['Vermont', 'VT'],['Virginia', 'VA'],['Washington', 'WA'],['West Virginia', 'WV'],['Wisconsin ', 'WI'],['Wyoming', 'WY']]
  # validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :street_1, presence: true
  validates :state, inclusion: { in: STATES_LIST.map{|a,b| b}, message: "is not valid state", allow_blank: true }
  validates :zip, presence: true, format: { with: /\A\d{5}\z/, message: "should be five digits long", allow_blank: true }
  validates :max_capacity, presence: true, numericality: { only_integer: true, greater_than: 0, allow_blank: true }
  
  # scopes
  scope :alphabetical, -> { order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  # callbacks
  before_destroy :verify_that_never_used_for_camps
  before_validation :get_location_coordinates

  def create_map_link(zoom=12,width=450,height=450)
    markers = ""; i = 1    
    markers += "&markers=color:red%7Ccolor:red%7Clabel:#{i}%7C#{self.latitude},#{self.longitude}"
    map = "http://maps.google.com/maps/api/staticmap?center= #{latitude},#{longitude}&zoom=#{zoom}&size=#{width}x#{height}&maptype=roadmap#{markers}&sensor=false"
  end


  private
  def verify_that_never_used_for_camps
    self.camps.empty?
  end

  def get_location_coordinates
    str = self.street_1
    zip = self.zip
    
    coord = Geocoder.coordinates("#{str}, #{zip}")
    if coord
      self.latitude = coord[0]
      self.longitude = coord[1]
    else 
      errors.add(:base, "Error with geocoding")
    end
    coord
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :set_student, only: [:show, :edit, :update, :destroy]
	before_action :check_login
	authorize_resource
	def index
	  @active_students = Student.active.alphabetical.paginate(:page => params[:page]).per_page(10)
	  @inactive_students = Student.inactive.alphabetical.to_a
	end

	def show
		@stu_camps=@student.camps
	  
	end


	def new
	  @student = Student.new
	end


	def edit
	end

	def create
	  @student = Student.new(student_params)
	  if @student.save
	    redirect_to @student, notice: "#{@student.proper_name} was added to the system"
	  else
	    render action: 'new'
	  end
	end

	def update
	  if @student.update(student_params)
	    redirect_to @student, notice: "#{@student.proper_name} was revised in the system."
	  else
	    render action: 'edit'
	  end
	end

	def destroy
	  @student.destroy
	  redirect_to students_url, notice: "#{@student.name} student was removed from the system."
	end


  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:first_name, :last_name, :date_of_birth, :rating, :active, :family_id, :camp_ids => [])
    end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_active_students.html.erb
<h3>Active Students</h3>

<table class="table">
  <tr>
    <th width="200">Name</th>
    <th width="200">Age</th>
    <th width="100">Rating</th>
    <th></th>
    <th></th>
  </tr>

<% @active_students.each do |student| %>
  <tr>
    <td><%= link_to student.name, student_path(student) %></td>
    <td align="center"><%= student.age %></td>
    <td align="center"><%= student.rating.zero? ? "Unrated" : student.rating %> </td>
    
    <td><%= link_to 'Edit', edit_student_path(student), class: "button tiny radius" %></td>
  </tr>
<% end %>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @active_students, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/students/_form.html.erb
<%= simple_form_for(@student, html: { class: 'form-horizontal' }) do |f| %>
       
    <div class="row">
      <div class="small-6 columns">
        <h3><%= controller.action_name.capitalize %> Student</h3>
        <%= f.input :family_id, collection: Family.active.alphabetical.map{|f| [f.family_name, f.id]}, prompt: "Select family..."  %>
        <%= f.input :first_name%>
        <%= f.input :last_name %>
        <%= f.input :date_of_birth, label: "Date_of_birth", as: :string, input_html: {:class => "avg datepicker"} %>
        <%= f.input :rating %>
        <%= f.input :active %>
      </div>
      <div class="small-1 columns">&nbsp;</div>
      <div class="small-5 columns">
        <% if controller.action_name=="edit" && @student.active %>
        <h3>Student Camp(s)</h3>
        <%= f.input :camp_ids, label: "", collection: Camp.active.chronological.map{|c| [c.name, c.start_date.strftime('%m/%d/%y')]}, as: :check_boxes %>
      <% end %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, class: 'button radius' %>
      <%= link_to 'Back to list of students', students_path, :class => 'button secondary radius' %>
    </div>

<% end %>

app/views/students/_inactive_students.html.erb
<% unless @inactive_students.empty? %>
  <div class="panel clearfix">
    <h5>Inactive Students</h5>
    <ul class="side-nav">
      <% @inactive_students.each do |student| %>
        <li><%= link_to student.name, student_path(student) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/students/_related_registrations.html.erb
<% unless @stu_camps.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel clearfix">
    <h5>Registered Camp(s)</h5>
    <ul class="side-nav">
      <% @stu_camps.each do |camp| %>
        <li><%= link_to camp.name,camp_path(camp)%> <%= "#{camp.start_date.strftime('%m/%d/%y')}" %></li>
      <% end %>
    </ul>
  </div>

<% else %>
  <div class="panel clearfix">
    <h5>No Registered Camp</h5>
  </div>
<% end %>

app/views/students/_student_details.html.erb
<h3>Student Details</h3><br />
<strong>Name:&nbsp;&nbsp;</strong> 
  <%= @student.proper_name %><br /><br />

<strong>Rating:&nbsp;&nbsp;</strong> 
  <%= @student.rating.zero? ? "Unrated" : @student.rating %> <br /><br />


<strong>Age:&nbsp;&nbsp;</strong> 
  <%= @student.age %> 
  <br /><br />

<strong>Birthday:&nbsp;&nbsp;</strong> 
  <%= @student.date_of_birth.strftime('%m/%d/%Y') %> 
  <br /><br />


<strong>Active?&nbsp;&nbsp;</strong>
  <%= @student.active ? "Yes" : "No" %><br /><br />





<%= link_to "Edit this student", edit_student_path(@student), class: "button tiny radius" %>&nbsp;&nbsp;

app/views/students/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/students/index.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "active_students" %>
    <br />
    <%= link_to "Add a new student", new_student_path, class: "button tiny radius" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'inactive_students' %>
  </div>
</div>

app/views/students/new.html.erb
<div class="row">
  <div class="small-8 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/students/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "student_details" %>
  </div>



  <div class="small-5 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'related_registrations' %>
  </div>
</div>