config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :families
  resources :locations
  resources :students
  

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout



  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # set the root url
  root to: 'home#index'

  # # Named routes
  # patch 'completed/:id' => 'tasks#complete', as: :complete
  # patch 'incomplete/:id' => 'tasks#incomplete', as: :incomplete
  
  # Last route in routes.rb that essentially handles routing errors
  get '*a', to: 'errors#routing'

end

app/models/family.rb
class Family < ActiveRecord::Base
  include ChessCampHelpers

  # relationships
  has_many :students
  has_many :registrations, through: :students

  # scopes
  scope :alphabetical, -> { order('family_name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  # validations
  validates_presence_of :family_name, :phone
  validates_format_of :phone, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"

  # callbacks
  before_save :reformat_phone
  before_destroy :is_never_destroyable
  

  def make_inactive
    self.active = false
    self.save!
  end
  
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
	before_action :set_family, only: [:show, :edit, :update, :destroy]
	before_action :check_login
	authorize_resource
	def index 
		@active_families = Family.active.alphabetical.paginate(:page => params[:page]).per_page(10)
		@inactive_families = Family.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
	end

	def show
		@students = @family.students.alphabetical.to_a
	end

	def new
	  @family = Family.new
	end
	def create
	 
	  @family = Family.new(family_params)
	  if @family.save
	    redirect_to @family, notice: "#{@family.family_name} family was added to the system."
	  else
	    render action: 'new'
	  end
	end


  def update

    if @family.update(family_params)
      redirect_to @family, notice: "#{@family.family_name} family was revised in the system."
    else
      render action: 'edit'
    end
  end


  def destroy
    @family.destroy
    redirect_to families_url, notice: "#{@family.family_name} family was removed from the system."
  end


  private
    def set_family
      @family = Family.find(params[:id])
    end

    def family_params
      params.require(:family).permit(:family_name, :parent_first_name, :email, :phone, :active)
    end



end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_active_families.html.erb
<h3>Active Families</h3>

<table class="table">
  <tr>
    <th width="200">Family Name</th>
    <th width="200">Parent First Name</th>
    
    <th width="200">Phone</th>
    </tr>

<% @active_families.each do |family| %>
  <tr>
    <td><%= link_to family.family_name, family_path(family) %></td>
    <td align="center"><%= family.parent_first_name%></td>
    <td align="center"><%= number_to_phone(family.phone) %></td>
    <td><%= link_to 'Edit', edit_family_path(family), class: "button tiny radius" %></td>
  </tr>
<% end %>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @active_families, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/families/_family_details.html.erb
<h3>Family Details</h3><br />
<strong>Family Name:&nbsp;&nbsp;</strong> 
  <%= @family.family_name %><br /><br />

<strong>Parent's First Name:&nbsp;&nbsp;</strong><br /> 
  <%= @family.parent_first_name %><br /><br />

<strong>email&nbsp;&nbsp;</strong> 
  <%= @family.email%><br /><br />

<strong>phone&nbsp;&nbsp;</strong> 
  <%= number_to_phone(@family.phone)%><br /><br />

<strong>Active?&nbsp;&nbsp;</strong>
  <%= @family.active ? "Yes" : "No" %><br /><br />



<%= link_to "Edit this Family", edit_family_path(@family), class: "button tiny radius" %>&nbsp;&nbsp;

app/views/families/_form.html.erb
<%= simple_form_for(@family, html: { class: 'form-horizontal' }) do |f| %>
   
   <h3><%= controller.action_name.capitalize %> Family</h3>
    
    <%= f.input :family_name %>
    <%= f.input :parent_first_name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :active %>

    <div class="form-actions">
      <%= f.submit nil, class: 'button radius' %>
      <%= link_to 'Back to list of families', families_path, :class => 'button secondary radius' %>
    </div>

<% end %>

app/views/families/_inactive_families.html.erb
<% unless @inactive_families.empty? %>
  <div class="panel clearfix">
    <h5>Inactive families</h5>
    <ul class="side-nav">
      <% @inactive_families.each do |family| %>
        <li><%= link_to family.family_name, family_path(family) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/families/_related_students.html.erb
<% unless @students.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel clearfix">
    <h5>Students belong to this family</h5>
    <ul class="side-nav">
      <% @students.each do |student| %>
        <li><%= link_to "#{student.name}", student_path(student) %></li>
      <% end %>
    </ul>
  </div>

<% else %>
  <div class="panel clearfix">
    <h5>No student belong to this family</h5>
  </div>
<% end %>

app/views/families/edit.html.erb
<div class="row">
  <div class="small-8 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/families/index.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "active_families" %>
    <br />
    <%= link_to "Add a new family", new_family_path, class: "button tiny radius" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'inactive_families' %>
  </div>
</div>

app/views/families/new.html.erb
<div class="row">
  <div class="small-8 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/families/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "family_details" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'related_students' %>
  </div>
</div>