config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :families
  resources :locations
  resources :students
  

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout



  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # set the root url
  root to: 'home#index'

  # # Named routes
  # patch 'completed/:id' => 'tasks#complete', as: :complete
  # patch 'incomplete/:id' => 'tasks#incomplete', as: :incomplete
  
  # Last route in routes.rb that essentially handles routing errors
  get '*a', to: 'errors#routing'

end

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About Us', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br /><br />
  <div id="copy">
    Webmaster: <%= mail_to("xiaotcao@gmail.com", "Xiaotian Cao", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2014
  </div>

app/views/partials/_nav.html.erb
  <div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
   
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <!-- options for curriculums -->
          <li class="has-dropdown">
            <%= link_to "Curriculums", curriculums_path %>
            <%  if logged_in? && current_user.role=="admin"%>
            <ul class="dropdown">
              <li><%= link_to "List Curriculums", curriculums_path %></li>
              <li><%= link_to "Add a Curriculum", new_curriculum_path %></li>
            </ul>
            <% else %> 
            <ul class="dropdown">
              <li><%= link_to "List Curriculums", curriculums_path %></li>
           
            </ul>
            <%end%>
          </li>

          <!-- options for camps -->
          <li class="has-dropdown">
            <%= link_to "Camps", camps_path %>
            <%  if logged_in? && current_user.role=="admin"%>
            <ul class="dropdown">
              <li><%= link_to "List Camps", camps_path %></li>
              <li><%= link_to "Add a Camp", new_camp_path %></li>
            </ul>
            <% else %> 
            <ul class="dropdown">
                <li><%= link_to "List Camps", camps_path %></li>
           
            </ul>
            <%end%>
          </li>

          <!-- options for instructors -->
          <li class="has-dropdown">
            <!-- <a href="#">Instructors</a> -->
            <%= link_to "Instructors", instructors_path %>
             <%  if logged_in? && current_user.role == "admin" %>
            <ul class="dropdown">
              <li><%= link_to "List Instructors", instructors_path %></li>
              <li><%= link_to "Add an Instructor", new_instructor_path %></li>
            </ul>
             <% else %> 
            <ul class="dropdown">
                <li><%= link_to "List Instructors", instructors_path %></li>           
            </ul>
            <%end%>
          </li>
          <!-- options for login -->
         
          <% if !logged_in? %>
            <li>
            <%= link_to "Click here to login", login_path%>
            </li>
          <% end %>

                   <!-- ADMIN ONLY OPTIONS -->
          <% if logged_in? && current_user.role == "admin" %>
            <li><%= link_to "Family", families_path %></li>
            <li><%= link_to "Students", students_path %></li>
            <li><%= link_to "Locations", locations_path %></li>
          <% end %>
        </ul>

        <% if logged_in? %>
          <ul class="right">
            <li class="has-dropdown">
            <%= link_to "Welcome, #{current_user.instructor.first_name}", user_path(current_user) %>
            <ul class="dropdown">
              <li><%= link_to "Edit settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Logout", logout_path %></li>
            </ul>
          </li>
        <% end %>

        </ul>
      </section>
    </nav>
  </div>

app/views/partials/_user_fields.html.erb
  <div class="fields">
    <div class="min_user">
      <!-- x icon to remove -->
      <%= f.link_to_remove("x") %>
      <!-- fields -->
     <%= f.input :username %>
  	 <%= f.input :password%>
   	 <%= f.input :password_confirmation %>
   	<%= f.label :Role %><br />
   	<%= f.select :role, User::ROLES, :prompt => "Select ..." %>

   	 <%= f.input :active %>
    </div>
  </div>