config/routes.rb
ChessCamp::Application.routes.draw do
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps
  resources :families
  resources :locations
  resources :students
  

  # Authentication routes
  resources :sessions
  resources :users
  get 'users/new', to: 'users#new', as: :signup
  get 'user/edit', to: 'users#edit', as: :edit_current_user
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout



  # semi-static routes
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy

  # set the root url
  root to: 'home#index'

  # # Named routes
  # patch 'completed/:id' => 'tasks#complete', as: :complete
  # patch 'incomplete/:id' => 'tasks#incomplete', as: :incomplete
  
  # Last route in routes.rb that essentially handles routing errors
  get '*a', to: 'errors#routing'

end

app/models/location.rb
class Location < ActiveRecord::Base

  # relationships
  has_many :camps

  # states list
  STATES_LIST = [['Alabama', 'AL'],['Alaska', 'AK'],['Arizona', 'AZ'],['Arkansas', 'AR'],['California', 'CA'],['Colorado', 'CO'],['Connectict', 'CT'],['Delaware', 'DE'],['District of Columbia ', 'DC'],['Florida', 'FL'],['Georgia', 'GA'],['Hawaii', 'HI'],['Idaho', 'ID'],['Illinois', 'IL'],['Indiana', 'IN'],['Iowa', 'IA'],['Kansas', 'KS'],['Kentucky', 'KY'],['Louisiana', 'LA'],['Maine', 'ME'],['Maryland', 'MD'],['Massachusetts', 'MA'],['Michigan', 'MI'],['Minnesota', 'MN'],['Mississippi', 'MS'],['Missouri', 'MO'],['Montana', 'MT'],['Nebraska', 'NE'],['Nevada', 'NV'],['New Hampshire', 'NH'],['New Jersey', 'NJ'],['New Mexico', 'NM'],['New York', 'NY'],['North Carolina','NC'],['North Dakota', 'ND'],['Ohio', 'OH'],['Oklahoma', 'OK'],['Oregon', 'OR'],['Pennsylvania', 'PA'],['Rhode Island', 'RI'],['South Carolina', 'SC'],['South Dakota', 'SD'],['Tennessee', 'TN'],['Texas', 'TX'],['Utah', 'UT'],['Vermont', 'VT'],['Virginia', 'VA'],['Washington', 'WA'],['West Virginia', 'WV'],['Wisconsin ', 'WI'],['Wyoming', 'WY']]
  # validations
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :street_1, presence: true
  validates :state, inclusion: { in: STATES_LIST.map{|a,b| b}, message: "is not valid state", allow_blank: true }
  validates :zip, presence: true, format: { with: /\A\d{5}\z/, message: "should be five digits long", allow_blank: true }
  validates :max_capacity, presence: true, numericality: { only_integer: true, greater_than: 0, allow_blank: true }
  
  # scopes
  scope :alphabetical, -> { order('name') }
  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  # callbacks
  before_destroy :verify_that_never_used_for_camps
  before_validation :get_location_coordinates

  def create_map_link(zoom=12,width=450,height=450)
    markers = ""; i = 1    
    markers += "&markers=color:red%7Ccolor:red%7Clabel:#{i}%7C#{self.latitude},#{self.longitude}"
    map = "http://maps.google.com/maps/api/staticmap?center= #{latitude},#{longitude}&zoom=#{zoom}&size=#{width}x#{height}&maptype=roadmap#{markers}&sensor=false"
  end


  private
  def verify_that_never_used_for_camps
    self.camps.empty?
  end

  def get_location_coordinates
    str = self.street_1
    zip = self.zip
    
    coord = Geocoder.coordinates("#{str}, #{zip}")
    if coord
      self.latitude = coord[0]
      self.longitude = coord[1]
    else 
      errors.add(:base, "Error with geocoding")
    end
    coord
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource

  def index
    @active_locations = Location.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    @inactive_locations =  Location.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
  	@camps = @location.camps.chronological.to_a

  end

  def new
  	@location = Location.new
  end

  def edit
  end

  def create
    @location = Location.new(location_params)
    if @location.save
      redirect_to @location, notice: "#{@location.name} location was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @location.update(location_params)
      redirect_to @location, notice: "#{@location.name} location was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_url, notice: "#{@location.name} was removed from the system."
  end

  private
    def set_location
      @location = Location.find(params[:id])
    end

    def location_params
      params.require(:location).permit(:name, :street_1, :street_2, :city, :state, :zip, :max_capacity, :active)
    end




end

app/helpers/locations_helper.rb
module LocationsHelper

end

app/views/locations/_active_locations.html.erb
<h3>Active locations</h3>

<table class="table">
  <tr>
    <th width="200">Name</th>
    <th width="200">Address</th>
    <th width="100">Capacity</th>
    <th></th>
    <th></th>
  </tr>

<% @active_locations.each do |location| %>
  <tr>
    <td><%= link_to location.name, location_path(location) %></td>
    <td align="center"><%= "#{location.street_1 } #{location.street_2} #{location.city}, #{location.state} #{location.zip}" %></td>
    <td align="center"><%= location.max_capacity %></td>
    <td><%= link_to 'Edit', edit_location_path(location), class: "button tiny radius" %></td>
  </tr>
<% end %>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @active_locations, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/locations/_camps_using.html.erb
<% unless @camps.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel clearfix">
    <h5>Location Used On:</h5>
    <ul class="side-nav">
      <% @camps.each do |camp| %>
        <li><%= link_to "#{camp.name}", camp_path(camp) %></li>
      <% end %>
    </ul>
  </div>

<% else %>
  <div class="panel clearfix">
    <h5>Location has not been used</h5>
  </div>
<% end %>

app/views/locations/_form.html.erb
<%= simple_form_for(@location, html: { class: 'form-horizontal' }) do |f| %>
   
   <h3><%= controller.action_name.capitalize %> Location</h3>
    
    <%= f.input :name %>
    <%= f.input :street_1 %>
    <%= f.input :street_2 %>
    <%= f.input :city %>
    <%= f.input :state, collection: Location::STATES_LIST, include_blank: true %>
    <%= f.input :zip %>
    <%= f.input :max_capacity %>
    <%= f.input :active %>

    <div class="form-actions">
      <%= f.submit nil, class: 'button radius' %>
      <%= link_to 'Back to list of locations', locations_path, :class => 'button secondary radius' %>
    </div>

<% end %>

app/views/locations/_inactive_locations.html.erb
<% if !@inactive_locations.empty? %>
  <div class="panel clearfix">
    <h5>Inactive Locations</h5>
    <ul class="side-nav">
      <% @inactive_locations.each do |location| %>
        <li><%= link_to location.name, location_path(location) %></li>
      <% end %>
    </ul>
  </div>
  <%else %>
  <p> We currently have no inactive location</p> 
<% end %>

app/views/locations/_location_details.html.erb
<h3>Location Details</h3><br />
<strong>Name:&nbsp;&nbsp;</strong> 
  <%= @location.name %><br /><br />

<strong>Address:&nbsp;&nbsp;</strong><br /> 

 <%= "#{@location.street_1 } #{@location.street_2} #{@location.city}, #{@location.state} #{@location.zip}" %>

<strong>Maximum Capacity&nbsp;&nbsp;</strong> 
  <%= @location.max_capacity %><br /><br />

<strong>Active?&nbsp;&nbsp;</strong>
  <%= @location.active ? "Yes" : "No" %><br /><br />

<strong>Map&nbsp;&nbsp;</strong>

<%= image_tag @location.create_map_link %>


<%= link_to "Edit this location", edit_location_path(@location), class: "button tiny radius" %>&nbsp;&nbsp;
<%= link_to 'Destroy location', location_path(@location), data: { confirm: 'Are you sure you want to permanently remove this location from the system?' }, method: :delete, class: "button tiny radius alert" %>

app/views/locations/edit.html.erb
<div class="row">
  <div class="small-8 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/locations/index.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "active_locations" %>
    <br />
    <%= link_to "Add a new location", new_location_path, class: "button tiny radius" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'inactive_locations' %>
  </div>
</div>

app/views/locations/new.html.erb
<div class="row">
  <div class="small-8 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/locations/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "location_details" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'camps_using' %>
  </div>
</div>